metal:
  children:
    masters:
      hosts:
        k8s-1-1: {ansible_host: 192.168.10.31, mac: '82:e5:86:d9:d2:2e', disk: sda, network_interface: ens18}
#k8s-1-2: {ansible_host: 192.168.10.32, mac: '36:56:b5:3b:a5:8d', disk: sda, network_interface: ens18}
#k8s-1-3: {ansible_host: 192.168.10.33, mac: '0e:08:b7:7a:e0:8f', disk: sda, network_interface: ens18}
#workers:
#hosts:
#k8s-1-4: {ansible_host: 192.168.10.34, mac: 'ba:93:7c:3e:74:09', disk: sda, network_interface: ens18}
